using WorkManagementSystem.Domain.Entities;
using WorkManagementSystem.Domain.Enums;
using WorkManagementSystem.Domain.Common;
using WorkManagementSystem.Infrastructure.Data;

namespace WorkManagementSystem.Tests.TestSupport;

internal sealed record RecurringTaskFixture(
    Unit Unit,
    User Manager,
    User Employee,
    Project Project);

internal static class RecurringTaskTestData
{
    public static async Task<RecurringTaskFixture> SeedAsync(AppDbContext context)
    {
        var now = new DateTime(2026, 8, 20, 8, 0, 0, DateTimeKind.Utc);
        var unit = new Unit
        {
            Id = Guid.NewGuid(),
            Name = $"Recurring Unit {Guid.NewGuid():N}"
        };
        var manager = CreateUser(
            unit.Id,
            SystemRoles.Manager,
            $"manager-{Guid.NewGuid():N}",
            $"MGR-{Guid.NewGuid():N}",
            now);
        var employee = CreateUser(
            unit.Id,
            SystemRoles.User,
            $"employee-{Guid.NewGuid():N}",
            $"EMP-{Guid.NewGuid():N}",
            now);
        var project = new Project
        {
            Id = Guid.NewGuid(),
            Name = $"Recurring Project {Guid.NewGuid():N}",
            Description = "Recurring task tests",
            UnitId = unit.Id,
            CreatedBy = manager.Id,
            CreatedAt = now
        };

        context.Units.Add(unit);
        context.Users.AddRange(manager, employee);
        context.UserUnits.AddRange(
            new UserUnit { Id = Guid.NewGuid(), UnitId = unit.Id, UserId = manager.Id },
            new UserUnit { Id = Guid.NewGuid(), UnitId = unit.Id, UserId = employee.Id });
        context.Projects.Add(project);
        await context.SaveChangesAsync();

        return new RecurringTaskFixture(unit, manager, employee, project);
    }

    public static async Task<RecurringTaskTemplate> AddTemplateAsync(
        AppDbContext context,
        RecurringTaskFixture fixture,
        DateTime nextRunAtUtc,
        bool isActive = true,
        bool useExplicitAssignee = true,
        RecurrenceType recurrenceType = RecurrenceType.Daily,
        int interval = 1,
        int? dayOfWeek = null,
        int? dayOfMonth = null)
    {
        var template = new RecurringTaskTemplate
        {
            Id = Guid.NewGuid(),
            UnitId = fixture.Unit.Id,
            ProjectId = fixture.Project.Id,
            Title = "Prepare recurring report",
            Description = "Generated by the recurring scheduler test.",
            Priority = TaskPriority.High,
            RequiresReview = true,
            PlannedEffortHours = 4m,
            RecurrenceType = recurrenceType,
            Interval = interval,
            DayOfWeek = dayOfWeek,
            DayOfMonth = dayOfMonth,
            NextRunAtUtc = DateTime.SpecifyKind(nextRunAtUtc, DateTimeKind.Utc),
            IsActive = isActive,
            CreatedByUserId = fixture.Manager.Id,
            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc)
        };
        context.RecurringTaskTemplates.Add(template);
        if (useExplicitAssignee)
        {
            context.RecurringTaskAssignees.Add(new RecurringTaskAssignee
            {
                Id = Guid.NewGuid(),
                TemplateId = template.Id,
                UserId = fixture.Employee.Id
            });
        }

        await context.SaveChangesAsync();
        return template;
    }

    private static User CreateUser(
        Guid unitId,
        string role,
        string username,
        string employeeCode,
        DateTime joinedAt)
    {
        return new User
        {
            Id = Guid.NewGuid(),
            Username = username,
            FullName = username,
            EmployeeCode = employeeCode,
            PasswordHash = "not-used",
            Role = role,
            UnitId = unitId,
            JoinedUnitAt = joinedAt,
            IsApproved = true
        };
    }
}
