// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkManagementSystem.Infrastructure.Data;

#nullable disable

namespace WorkManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711123000_KpiPeriodsWorkHistory")]
    partial class KpiPeriodsWorkHistory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
